name: Example 3- checkout

on: push

jobs:
    checkout-demo:
        runs-on: ubuntu-latest
        steps:
         - name: checkout repo
           uses: actions/checkout@v4
        
         - name: List files after checkout
           run:  ls -lrth

         - name: show current working directory
           run:  pwd
         - name: print contents of a file
           run:  cat .github/workflows/example-3.yml